### ISSUE TITLE
Double colon when message starts with colon

### ISSUE THREAD

**Issue by galfert** [sockethub/sockethub-platform-irc#29] opened 2017-06-16 14:13 UTC
As already reported in 67P/hyperchannel#91, messages that start with a colon, get sent with 2 colons.

E.g.  the message `:)` will be sent as `::)` to IRC.

**Comment by galfert** [comment] 2017-06-16 14:35
I traced this down to a hack I found in `irc-factory`: https://github.com/ircanywhere/irc-factory/blob/6a7f739bda7fe3a6c6201edce2fab64699c17167/lib/irc.js#L1214-L1220

Apparently it tries to circumvent a bug in `irc-socket`.

Looks like that bug in `irc-socket` doesn't exist anymore in newer versions. But I'm a little bit confused about the dependency declarations.

`irc-factory` is using their own fork of `irc-socket` (ircanywhere/irc-socket) as dependency, which seems to be based on `irc-socket` version 2.4.0. I assume that version still has the bug that the hack is for.

`sockethub-platform-irc` defines their own dependency on `irc-socket`, using version 3.0.7. This version doesn't seem to have that bug anymore, so the hack wouldn't be needed anymore.

My question now is: does `irc-factory` now use the `irc-socket` version that `sockethub-platform-irc` defines instead of their own? Because it looks to me like the two versions have different constructors, with the newer version (3.0.7) requiring more option fields than the old version.

@silverbucket: why does `sockethub-platform-irc` have a dependency on `irc-socket`? I didn't find any place where it's actually used.

**Comment by galfert** [comment] 2017-06-28 13:22
@silverbucket any insights about this?

**Comment by silverbucket** [comment] 2017-06-28 13:47
@galfert - seems like a tangled mess. The reason I added `irc-socket` as a dependency a few weeks ago was because I was getting consistent travis fails with `npm` regarding that dependency and I couldn't figure out any other way to address it. I still am not sure what is going on there, it was rather difficult to debug as travis was giving me no information that just `irc-socket` not being found, which was not reproducible on my system.

**Comment by silverbucket** [comment] 2017-06-28 13:49
Add to that, it appears @rickihastings has abandoned `irc-factory` altogether. Perhaps we should consider forking it an just bringing the version discrepancies and inconsistencies in line, otherwise maintenance and bug fixing mode?

**Comment by galfert** [comment] 2017-06-28 14:11
Ok, I see. I will check how much work it would be to update `irc-factory` to use the most recent `irc-socket`.

**Comment by galfert** [comment] 2017-07-07 18:29
Small update: I started converting `irc-factory` to use the new version of `irc-socket`. But so far I still haven't gotten the tests to run properly.

**Comment by silverbucket** [comment] 2018-01-11 12:30
@galfert did you ever get anywhere with this?

**Comment by galfert** [comment] 2018-01-12 10:59
No, unfortunately not. I have some local changes, but the tests still don't run or are failing silently without any error messages.

So far my only changes are the adaptations to the new constructor. If you want to have a look yourself, I can push that somewhere.

**Comment by silverbucket** [comment] 2018-01-12 12:58
@galfert did you ever get anywhere with this?

**Comment by silverbucket** [comment] 2018-09-21 10:20
since we use `irc-socket` directly now, closing this. (sockethub milestone v3.0)

**Closed by silverbucket** 2018-09-21 10:20 UTC
Labels: bug
