### ISSUE TITLE
No notification about nick being registered, other nick being assigned automatically

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub-platform-irc#7] opened 2015-05-24 11:43 UTC
When using a nick that is registered with NickServ, instead of asking for a password or even saying anything at all about it, another nickname (usually "[originalname]1") is assigned on the IRC server.

Hyperchannel is currently failing horribly in this case, because it can't know to even change its own nickname and IDs accordingly, so when this happens you're in a middle state, where it thinks it's [originalname], yet sends and receives messages via Sockethub as [originalname]1.

Ideally we can ask the user for the password when the nick is taken, similar to what most native IRC clients do (but with a nicer UI than asking to IDENTIFY of course).

**Comment by silverbucket** [comment] 2015-05-24 21:57
Hmm, what about if sockethub sends a JSON object indicating a name change (`update` verb)... Like:

```
{
{
  "@type": "update",
  "context": "irc",
  "actor": {
    "@id": "irc://foobar@irc.freenode.net",
    "@type": "person"
  },
  "target": {
    "@id": "irc://foobar1@irc.freenode.net",
    "@type": "person"
  }
}
```

Sockethub can do a check after connection on the resulting JSON to make sure the actor and actual names match, if not, it can send an `update`

**Comment by skddc** [comment] 2015-05-26 14:25
In clients I used thus far, the experience is much nicer, in that NickServ will tell you your name is registered and ask you to IDENTIFY, instead of just changing your name without telling you.

Later on, we need to hide NickServ completely, as we already discussed and planned, and for that it would also be helpful to get this information in a specific way, as opposed to an incoming name change from the server.

**Comment by silverbucket** [comment] 2015-05-26 14:52
If i'm not mistaken, even if you get a message from NickServ telling you the name requires identification, you are still temporarily assigned a different nick, ie `slvrbckt_` until you identify.

**Comment by skddc** [comment] 2015-05-26 14:59
As far as I remember, there's a short grace period where it doesn't change, which is why things like e.g. sending money via only IRC nicknames as identification is a bad idea.

**Comment by silverbucket** [comment] 2015-08-15 11:52
Asked for more info upstream: https://github.com/ircanywhere/irc-factory/issues/33

**Comment by skddc** [comment] 2015-11-03 09:13
This is probably the most important issue for Kosmos at the moment. Bump. :)

**Comment by silverbucket** [comment] 2015-11-03 13:51
@skddc Do you know of any command which we could use to query for this information? It could either be done in the platform code itself or from the client, but as far as I can tell there's no data that is coming in from the IRC server to indicate nick state. So if we can figure out a way to ask the server that seems like the best bet at this point.

**Comment by skddc** [comment] 2015-11-03 13:55
We could solve most of it by hacking things up in Hyperchannel I guess, but it'd be much nicer to solve it in the platform I think.

**Comment by silverbucket** [comment] 2015-11-03 13:57
I agree, since it's fairly protocol-specific behavior in the first place. Just wondering what steps we'd need to carry out, and how we should handle it (both to the irc server, and more importantly how it should behave to the client).

**Comment by silverbucket** [comment] 2016-01-08 21:48
This is fixed now in this commit https://github.com/sockethub/sockethub-platform-irc/commit/75cfa2bfe90d64fae5dad9094d6cdc0ebc9cdfbe (mentioned wrong issue in that commit message though).

**Comment by silverbucket** [comment] 2016-01-08 21:51
This is fixed now in this commit https://github.com/sockethub/sockethub-platform-irc/commit/75cfa2bfe90d64fae5dad9094d6cdc0ebc9cdfbe (mentioned wrong issue in that commit message though).

**Comment by galfert** [comment] 2016-01-08 22:59
I just talked to @silverbucket about this and he realized that the fix is probably not working as intended. Reopening.

**Comment by silverbucket** [comment] 2016-01-12 02:01
So, after verifying the behavior on a few different scenarios and IRC servers other than freenode, I can verify this fix does actually work. re-closing.

**Closed by silverbucket** 2016-01-12 02:01 UTC

**Comment by skddc** [comment] 2016-01-12 04:20
![success](https://cloud.githubusercontent.com/assets/842/12254705/bd43e632-b8b9-11e5-9c78-67e3c4607bd6.gif)
